---
# Configuration directives for Travis CI
# --------------------------------------

# [Travis CI] http://travis-ci.org
# [configuration] http://about.travis-ci.org/docs/user/build-configuration/
services: docker

env:
  - distro: ubuntu1804
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: debian9
    playbook: test.yml
  - distro: debian8
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false


  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/arnobirchler/627e4655465b696a0b521a560bc2206f/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/